#     _    _              _ _                   _  #
#    / \  | | ____ _ _ __(_) |    _____   _____| | #
#   / _ \ | |/ / _` | '__| | |   / _ \ \ / / _ \ | #
#  / ___ \|   < (_| | |  | | |__|  __/\ V /  __/ | #
# /_/   \_\_|\_\__,_|_|  |_|_____\___| \_/ \___|_| #

# 插件文档: https://cpjinan.github.io/Wiki/

##################################
#       AkariLevel  Config       #
##################################

###########
# Options #
###########

# 全局设置
Options:
  # 语言
  Language: "zh_CN"
  # 配置文件版本
  Config-Version: 6
  # 检查版本更新
  Check-Update: true
  # OP 版本更新通知
  OP-Notify: true
  # 启用 bStats 统计
  Send-Metrics: true
  # 启用调试模式
  Debug: false

############
# Database #
############

# 数据存储设置
Database:
  # 使用玩家 UUID 进行存储
  UUID: false
  # 存储方式 (JSON, SQL)
  Method: JSON
  JSON:
    file: database.json
  SQL:
    host: localhost
    port: 3306
    user: root
    password: password
    database: minecraft
    table: akarilevel